apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  labels:
    app: login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: leeinhong9512/panda-login:720066b64d26dbff1d0bb3a0c66f429609f9f1ab
        ports:
        - containerPort: 8080  # 예시 포트, 필요에 따라 변경
        volumeMounts:
        - name: login-storage
          mountPath: /app  # PVC를 마운트할 경로
      volumes:
      - name: login-storage
        persistentVolumeClaim:
          claimName: login-pvc  # 위에서 생성한 PVC 이름
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: bidloginports:
    - protocol: TCP
      port: 8084  # 서비스에 노출되는 포트
      targetPort: 8081  # 파드에 포워딩되는 포트
      nodePort: 31300  # 변경 가능: 노드 포트 번호 (30000 ~ 32767 사이의 값을 선택)
  type: NodePort  # 서비스 유형을 NodePort로 변경
  
